### ISSUE TITLE
npm pack is exiting with an error

### ISSUE THREAD

**Issue by drwlrsn** [FormidableLabs/publish-diff#9]
I am trying to use publish-diff for the first time and I also happen to be using an npm registry setup in Nexus. When I attempt to `publish-diff -n .` I get the following error:

```
Error: 'npm pack . --registry https://nexus.repo/repository/npm-all/' exited with error code: 235
    at ChildProcess.<anonymous> (/Users/user/.nvm/versions/node/v6.9.5/lib/node_modules/publish-diff/lib/package.js:74:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

My .npmrc looks like:
```
registry=https://nexus.repo/repository/npm-all/
_auth="<key>"
email=npm@nexus.repo
always-auth=true
```

Are there any setup steps I am missing for a private registry?

**Comment by ryan-roemer** [comment]
Can you try:

```sh
$ publish-diff
```

Straight up and see if that works?

If it doesn't, can you try:

```sh
$ npm pack .
#  .... and ...
$ npm pack <NAME_OF_PUBLISHED_MODULE>
```

and let me know for both if they succeed?

**Comment by ryan-roemer** [comment]
Oh, and what is the full path to your `.npmrc` file and full path to your project?

**Comment by drwlrsn** [comment]
The first returns nothing:
```
$ publish-diff

```

Both `pack` commands succeed:
```
$ npm pack .
package-1.0.0-rc.1.tgz
$ npm pack skip-api
package-1.0.0-rc.1.tgz
```

**Comment by ryan-roemer** [comment]
@drwlrsn -- Can you pull down and try out https://github.com/FormidableLabs/publish-diff/pull/10 and see if that fixes your problems?

**Comment by drwlrsn** [comment]
Oh yah it totally does. Wow thanks for figuring that out.
